spring:
  application:
    name: Spring demo

  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    driverClassName: org.postgresql.Driver
    username: demo_username
    password: demo_password

  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: update

user-application:
  base-url: http://localhost:8081