name: Maven github pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: check folder
        run: ls -la
      - name: Go to spring folder
        run: cd spring-demo
      - name: check folder
        run: ls -la
      - name: Build with Maven
        run: cd spring-demo && ls -la && mvn -B package --file pom.xml
